### ISSUE TITLE
Can't compile under archlinux / find gjson package

### ISSUE THREAD

**Issue by jptrzy** [nahuelwexd/Replay#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I compile it with `meson setup` it outputs:

```
...

Run-time dependency libadwaita-1 found: YES 1.2.2
Run-time dependency gee-0.8 found: YES 0.20.6
Run-time dependency gio-2.0 found: YES 2.74.5
Run-time dependency gjson-1.0 found: NO (tried pkgconfig)

../src/meson.build:28:0: ERROR: Dependency "gjson-1.0" not found, tried pkgconfig
```

I can't also find this package in archlinux aur or even on any git server.

Could you specify which library I need?

### OS

Artix (Archlinux)

### Version

newest one

### Installation method

None

**Comment by rhysperry111** [comment]
Possibly this? https://github.com/tidwall/gjson

**Comment by jptrzy** [comment]
I installed it with `go install`, but it don't look like the right one.

**Comment by nahuelwexd** [comment]
I would suggest reading the Flatpak manifest next time.

https://gitlab.gnome.org/BZHDeveloper/vul

**Comment by jptrzy** [comment]
Thank you.

I installed it after using `meson configure -Dprefix=/usr` to change meson prefix from /usr/local to /usr.
