### ISSUE TITLE
Ideas for a new name :D

### ISSUE THREAD

**Issue by nahuelwexd** [nahuelwexd/replay#5]
Ah, here we go...

# Some of history

The name for this project, was inherited from a time where I was developing for UWP. I selected that name 'cause I was developing an "universal" application and it was a YouTube app so: Universal + YouTube = UniTube. Time later, Unigram was here, a Telegram client for Windows... Since then I'm trying to think a name to avoid the confusion that it may be related in some way to that project.

Fast forward to 2020, I'm on Linux since a few years, and I'm in love with GTK and GNOME, so I decided to restart my almost dead project again, but as a really universal app (multiplatform I mean) this time, using GTK and developing it as a GNOME app. But the name is still an outstanding account... So here we are :D

# Things to consider

The new name should be attractive and should follow this rules:

- Consist of one or two simple nouns
- Be related to YouTube
- Be short (less than 15 characters)
- Be easy to pronounce
- Use title case
- Do not use trademarks or names of other projects
- Not having a “G” prefix
- Not be a complicated name or an acronym
- Not made-up words or word combinations (sadly, the current one)

(those rules are extracted from [this excellent article](https://blogs.gnome.org/tbernard/2019/04/26/naming-your-app/) written by Tobias Bernard)

# Proposed names

**By @3eloa**:
Cima

**By @bertob**:
Streams, Visor, Channels, Telly, Telecast

**By @wada3n**:
Cassette, Telegenic, Resume

**By me**:
Overflow, Replay

**By a friend of mine**:
Filmo

### Let's go :D

**Comment by nahuelwexd** [comment]
Some ideas that I have....

- "Flow" is a cool name: Related to streaming, and YouTube consists in videos being streamed... But sadly is already [taken on my country](https://cablevisionflow.com.ar).
- "Overflow" maybe? Still related to streaming and means a big flow, as the big flow of videos that you will see on the app?
- "Replay"... Related to videos, cause YouTube is about videos. You will want to replay some youtube videos over and over again. Maybe I should need to update the app icon :thinking: 
- "Express", related to the basics of YouTube: express yourself, broadcast yourself. YouTube was designed as a way to express and share yourself with others through a video... But taken by a [JavaScript framework](https://expressjs.com)

**Comment by 3eloa** [comment]
I'm not good at that but i will try .
What do you think 

- (Tube With Me)

TubeWme , TubeWMe , TWMe ,TUWM ,TUWMe , twme,TWme,
(Tuby) ,(Tubme) ,😣😣😣😣 🤔🤔 look at that  ---->>>>>>Cima , Cimahub , livetube , Tube4u Tube4Me , Vidit ,VidPlay , Vidground .
As i say I'm not good for that at all but i tried 😊😊😊

**Comment by nahuelwexd** [comment]
@3eloa hehe, thanks :smile:

But using "tube" could bring legal complications since it is part of the YouTube name (Although the app itself can bring legal complications sooner or later :laughing:)

It was preferable not to use combinations of different existing words, so of all your suggestions, the only one that really caught my attention was "cima". What reasoning did you use to suggest it and how does it relate to YouTube?

**Comment by 3eloa** [comment]
In the first I am from Egypt and we in Egypt call cinma ->>cima without n and no application has that name at all so cinma or cima means the place to see videos and films and your Application too do the cima or cinma work so that was the reason😊😊😊, sorry for bad English 😅😅😅

**Comment by nahuelwexd** [comment]
@3eloa Nice idea :D It's a very original name

**Comment by nahuelwexd** [comment]
A close friend suggested I use "Filmo", a Latin word that means "film" which links it to an app that plays videos

**Comment by bertob** [comment]
Replay sounds pretty nice!

A few additional ideas I brainstormed:

- Streams
- Visor
- Channels
- Telly
- Telecast

**Comment by wada3n** [comment]
Replay & Cima seems like a good names!
Here are some suggestions as well:
Cassette
Telegenic
Resume

**Comment by nahuelwexd** [comment]
After having consulted with various people, some close friends of mine and thinking about it, I am among these names to be placed in the app:

Cassette, Streams, Replay, Telecast and Cima

I think names like Cassette or Replay could represent changes to the app icon, especially Cassette :thinking:

What do you think?

**Comment by wada3n** [comment]
Cassette😊️, Yes indeed!
it's such a beautiful name :smiling_face_with_three_hearts:

**Comment by bertob** [comment]
My favorites are Replay and Telecast

**Comment by nahuelwexd** [comment]
I think I will end up choosing "Replay", but changing it to "Replay it". Cassette I like it, but it seems to me that it would require a change to the icon to make it a cassette (redundancy worth it), and the Podcast icon is already one, so it would be quite a copy in my opinion.

If you have any argument that can change my mind, I will be happy to "hear it"

**Comment by bertob** [comment]
"Replay it" sounds a bit weird, and not really like an app name.

**Comment by nahuelwexd** [comment]
> "Replay it" sounds a bit weird, and not really like an app name.

So "Replay" is ok but "Replay it" is not ok 🤔

**Comment by wada3n** [comment]
I think we should get away from the cassette icon just like in podcasts.
Coming up with a different design gives an indication of the type of app without being direct.
The name "_**Cassette**_" does not have to be an indication of the icon, but it only means symbolic, suggestive, and perhaps surreal, and this is enough, while the icon indicates the type of the app in my opinion.
🤓️

**Comment by nahuelwexd** [comment]
@wada3n I like the idea that app icons are related in some way to their name, such as Builder having a robotic arm as an icon; Nostalgia, which has an old monitor as an icon, evoking nostalgia for those old times; Celluloid, whose icon is a piece of tape (which was made of this material) and on it placing the playback controls; or Lollypop, whose icon is literally a lollipop with a play icon

The current icon of this application is supposed to be the YouTube player itself, with its playbar, buffer and play button to continue watching the video. With "Replay" I proposed to change the icon from play to replay, just to evoke the name.

Besides this, I still cannot fully understand the metaphor transmitted through "Cassette", mainly because I was not contemporary with the cassettes, so the only image I have of them is my father's music cassettes.

I also do not want to rule out cassette, because I did a poll on Telegram to know a little the opinion on the current suggestions, and Cassette won, Replay being in second place.

![poll that I made in Telegram](https://user-images.githubusercontent.com/18204745/82233448-6a454700-9906-11ea-9140-8d16381f0fe5.png)

**Comment by bertob** [comment]
> So "Replay" is ok but "Replay it" is not ok thinking

"Replay" is a single word, the other one is more of a phrase, which is very unusual for app names.

**Comment by wada3n** [comment]
@nahuelwexd It is true that the icon will be beautiful, to be attached to the name, but it is possible to deviate from this frame and hit two birds with one stone.
As for the name, the metaphor lies in the cassette box and its contents, and its relation to the historical and nostalgic effect, And how it was very widespread, as is YouTube now!
The name attracts everyone who hears or reads it.

**Comment by wada3n** [comment]
The artist @bertob   is creative, what if he tries to give us something with icons, until we see the results about the two names.
If possible, of course

**Comment by nahuelwexd** [comment]
Well, after a long time thinking, some time designing some logos and so on ... I finally decided to use Replay as the name for the app. The logo will remain unchanged for now, but I'll update the symbolic (which reflects one of the previous logo designs).

Thanks to @bertob, @wada3n and @3eloa for your ideas :wink: It has been a pleasant experience to meet people interested in my project

**Comment by wada3n** [comment]
Very cool.
Waiting for the first release of the app, I'm sick of browsers consuming resources the unnatural way.
I wish you the best always @nahuelwexd
