### ISSUE TITLE
Decide which method we will use to obtain the data

### ISSUE THREAD

**Issue by nahuelwexd** [nahuelwexd/Replay#55]
I open this issue for discussion.

Currently there are several ways in which Replay could obtain the data:

- YouTube Data API (unpopular option for privacy lovers)
- The Invidious API
- Literally download YouTube web and parse data locally

Which method should be appropriate to use in this app? Which is the one that will hold up best in the long run?

**Comment by tutitau** [comment]
doesn't [youtube-dl](https://github.com/ytdl-org/youtube-dl) do the job ?

**Comment by nahuelwexd** [comment]
> doesn't [youtube-dl](https://github.com/ytdl-org/youtube-dl) do the job ?

@tutitau Well, this issue is about retrieving YouTube data like: current trending videos, searchs, channel metadata, channel videos, channel playlists, and so on.

youtube-dl is just helping with retrieving the actual video, and yes, I'm going to use it for that.

**Comment by jannuary** [comment]
does invidious allow one to log in and use their google account?

**Comment by nahuelwexd** [comment]
@jannuary The only one that allows you to use your Google account is the YouTube Data API v3

Invidious has its own account system, not related to Google at all

**Comment by nahuelwexd** [comment]
Well, after having recent discussions involving both @tchx84 and @Marko2019 (not necessarily both at the same time) on Telegram, I made the decision to use [Invidious](https://invidious.io) to get the data needed to nurture the app. In the future, the possibility of adding YouTube Data API as an option will be analyzed for those who prefer to continue maintaining a way to synchronize Replay with their data from their Google account.

Also, since Invidious doesn't have a central instance, but draws on the different instances created by the community, https://api.invidious.io will be used to obtain a list of the best instances according to their health.

**Comment by nahuelwexd** [comment]
> @lifeiscontent: you could create a facade for the data API. And if the user is logged out use the more privacy focused API and if the user prompts to sign in, use google APIs if they’re logged in
