### ISSUE TITLE
Should we move Replay-Design here?

### ISSUE THREAD

**Issue by nahuelwexd** [nahuelwexd/Replay#57]
Currently the repo where the designs live is somewhat separate from the app's repo. Should we consider moving it here and keeping it as an extra branch? Or maybe in a special folder within the project tree?

**Comment by nahuelwexd** [comment]
I'll move the designs here, but in a `designs` branch

**Comment by lifeiscontent** [comment]
@nahuelwexd Why not in the main branch in a design folder?

**Comment by nahuelwexd** [comment]
@lifeiscontent I prefer to have both separately. Also, that way I can make use of git worktree to have main and design in two separate folders

**Comment by lifeiscontent** [comment]
@nahuelwexd I’m curious why though, for me personally if I want to look at designs I then have to stash my changes, check out a branch, store the designs locally, go back to my branch, unstash my changes and continue my work

**Comment by nahuelwexd** [comment]
`git worktree ../Replay-Design design`

That way I would end having:
- `Replay` => The folder with `main` branch
- `Replay-Design` => The folder with `design` branch

And both strictly related, so a commit in one would appear in the other

**Comment by lifeiscontent** [comment]
@nahuelwexd Oh, I’m not familiar with worktree in git, I’ll need to read up on it

**Comment by nahuelwexd** [comment]
@lifeiscontent I found out about worktree with a blog post by jimmac: https://blog.jimmac.eu/2021/git-worktree

Here is the documentation anyway: https://git-scm.com/docs/git-worktree

**Comment by nahuelwexd** [comment]
Well, it's done

https://github.com/nahuelwexd/Replay/tree/design
