### ISSUE TITLE
No elements in window

### ISSUE THREAD

**Issue by rhysperry111** [nahuelwexd/replay#6]
Hi, I am in the process of making the AUR package and haven't been able to get it to work succesfully.
This is what it looks like (sorry for using custom theme):
![screenshot@2020 05 14-12:10:39](https://user-images.githubusercontent.com/28820694/81927667-f04a5080-95db-11ea-8a7a-542f4617116a.png)

I have the following dependecies:
- Unitube-gtk-git: b43cd30-1 (this is the WIP AUR package)
- libgee: 0.20.3-2
- gtk3: 1:3.24.20-1
- libhandy-git: 0.0.13.r270.gc100c7e-1

**Comment by nahuelwexd** [comment]
I know that currently is only an empty window. It was actually something I told you in #4

> or at least in a version that would be useful for someone, since currently it is only an empty window hehe 😅

The image shown in the README is a mockup (maybe I should clarify that), and the app is currently at a very early stage of development.

**Comment by rhysperry111** [comment]
Ahh, sorry. Completely my mistake.

Good luck with the project! I am eager to see it progress

**Comment by nahuelwexd** [comment]
Reopening to mark it as a pending task ;)
