### ISSUE TITLE
Implement the videos page

### ISSUE THREAD

**Issue by nahuelwexd** [nahuelwexd/Replay#70]

**Comment by jannuary** [comment]
There have been design iteration in the telegram, available [here](https://www.figma.com/file/xzRerALc10Xf4Gr2rRfbMH/Polyphony-Replay?node-id=386%3A1997), with an interactive prototype [here](https://www.figma.com/proto/xzRerALc10Xf4Gr2rRfbMH/Polyphony-Replay?node-id=386%3A1998&viewport=572%2C333%2C0.3242415487766266&scaling=min-zoom&page-id=386%3A1997&starting-point-node-id=228%3A1649).
